"""Wearable data provider abstraction for VIGIL AI — Phase 5.

Demo mode uses the simulated provider, which is deterministic and marked
`source: "simulated"`. Live mode plugs in a real provider later:

    class PartnerAPIProvider:
        def daily(self, user_id, days): ...   # rows shaped like wellness_data

The provider NEVER decides anything medical — it only supplies readings.
Interpretation stays in wellness_insights(), which is deliberately
non-diagnostic and supportive in tone.
"""
from __future__ import annotations

import config


class SimulatedProvider:
    """Reads the demo store — data generated by demo_data at seed time."""
    name = "simulated"

    def daily(self, user_id: str, days: int = 14) -> list:
        import data_store
        rows = data_store.find("wellness_data", lambda w: w["user_id"] == user_id)
        rows.sort(key=lambda w: w["recorded_at"])
        return rows[-days:]


def get_provider():
    """Live mode will select a partner provider via config; demo stays simulated."""
    if config.MODE == "demo":
        return SimulatedProvider()
    # Live providers arrive in the final integration phase, e.g.:
    #   if config.INTEGRATIONS.get("wearable_provider") == "partner": return PartnerAPIProvider()
    return SimulatedProvider()
